---
abstract: '(DEPRECATED) Make Time::Duration support milliseconds'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-Duration-Patch-Millisecond
requires:
  Module::Patch: 0.12
  Time::Duration: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/dist/Time-Duration-Patch-Millisecond
  repository: http://github.com/sharyanto/perl-Time-Duration-Patch-Millisecond
version: 0.03
